# Generated by Django 2.2 on 2020-03-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_collectcount_collectrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectrecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='collectrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollectCount',
        ),
        migrations.DeleteModel(
            name='CollectRecord',
        ),
    ]
